services:
  db:
    container_name: "postgres-db-devops"
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: camunda
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5438:5438
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#
#  backend:
#    container_name: "Backend"
#    image: studentrcm:latest
#    build: ./StudentCRM
#    depends_on:
#      - postgres
#    ports:
#      - 8088:8088
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5438/postgres
#      SPRING_DATASOURCE_USERNAME: admin
#      SPRING_DATASOURCE_PASSWORD: admin
#
#volumes:
#  postgres-data:
#    driver: local