# If spring.datasource is enabled, the processes, DMNs, process instances, etc. are backed up after a reboot
spring.datasource:
  url: jdbc:h2:mem:camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password: sa
spring.h2.console.enabled: true

camunda.bpm:
  admin-user:
    id: d
    password: d
    firstName: Demo
    lastName: Demo
  filter:
    create: All tasks
server.port: 8080