#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/camunda-training;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:

spring.datasource:
  url: jdbc:h2:mem:camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  #shareable h2 database: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
  username: sa
  password: sa
spring.h2.console.enabled: true

camunda:
  bpm:
    database.schema-update: false
    job-execution:
      deployment-aware: true
    admin-user:
      id: d
      password: d
      firstName: Demo
    filter:
      create: All tasks