#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/camunda-training;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:

spring.datasource:
#  url: jdbc:h2:mem:camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  url: jdbc:postgresql://localhost:5342/postgres-DB-devops
  #shareable h2 database: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
  username: admin
  password: admin
#spring.h2.console.enabled: true

camunda:
  bpm:
    database.schema-update: false
    job-execution:
      deployment-aware: true
    admin-user:
      id: d
      password: d
      firstName: Demo
    filter:
      create: All tasks

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresQLDialect