server:
  port: 8090

spring:
  application:
    name: camundapostgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5342/camunda
    username: admin
    password: admin

  hikari:
    jdbc-url: jdbc:postgresql://localhost:5432/camunda
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    pool-name: CAMUNDA-HIKARI-POOL
    idle-timeout: 3000
    minimum-idle: 30
    maximum-pool-size: 10
    connection-timeout: 2000
    connection-test-query: select 1
    transaction-isolation: TRANSACTION_READ_COMMITTED

camunda:
  bpm:
    enabled: true

    admin-user:
      id: d
      password: d
      firstName: Sarah
      lastName: Kaiser

    database:
      schema-update: true

    filter:
      create: All tasks

    authorization:
      enabled: true

    history-level: full

    auto-deployment-enabled: true

    default-number-of-retries: 3

    job-execution:
      enabled: true

    webapp:
      application-path: /camundapostgres








