# If spring.datasource is enabled, the processes, DMNs, process instances, etc. are backed up after a reboot
#
#spring.datasource:
#  url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#  #shareable h2 database: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
#  username: sa
#  password: sa
#spring.h2.console.enabled: true

spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm:
  admin-user:
    id: d
    password: d
    firstName: Demo
    lastName: Demo
  filter:
    create: All tasks
#  database:
#    schema-update: false
#    schema-name: camunda
#    table-prefix: camunda.
#  default-serialization-format: application/json
server.port: 8080